<?php
$translate = $this->plugin('translate');
$navDepth = (int) $this->themeSetting('nav_depth') ? (int) $this->themeSetting('nav_depth') -1 : -1;
?>

<header class="main-header">

	<?php echo $userBar; ?>

	<div class="main-header__top-bar container">
		<div class="main-header__search-form">
			<?php echo $this->partial('common/search-form'); ?>
		</div>
							<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>"  style="max-width: 200px;float:right;margin-left:10px;"/>
			<?php endif; ?>
	</div>
	<hr class="alignfull">

	<div class="main-header__main-bar container">
		<h1 class="main-header__site-title site-title">
		 <?php if ($this->themeSetting('header_layout')==='combo'): ?>
 
			<a href="<?php echo $site->url(); ?>">
 			
 			<h1><?php echo $this->escapeHtml( $site->title() ); ?></h1>
 			
			</a>
 
 
 <?php else: ?>
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>" />
			<?php else: ?>
				<?php echo $this->escapeHtml( $site->title() ); ?>
			<?php endif; ?>
			</a>
			<?php endif; ?>
		</h1>

		<nav class="main-navigation">
			<div class="main-navigation__container">
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'addClassToListItem' => true,
					'maxDepth' => $navDepth
				]);
				?>
			</div>
			<button
				 class="main-navigation__toggle"
				 aria-expanded="false"
				 aria-controls="menu-drawer">
				<span class="sr-only">Open menu</span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</button>
		</nav>

		<?php echo $this->partial('common/menu-drawer'); ?>
	</div>

</header>
