<!-- 
exception
-->

<?php 
$sites = $item->sites();

if (count($sites) > 0) {
    if (in_array($site, $sites)) {
      echo $this->headMeta()->appendName('robots', 'index');
    } else {
      echo $this->headMeta()->appendName('robots', 'noindex');
    }
  } else {
    echo $this->headMeta()->appendName('robots', 'noindex');
  }
?> 



<?php $itemIdCheck = $item->id()?>

<?php if ($itemIdCheck == 4850 or $itemIdCheck == 4879 or $itemIdCheck == 4896 or $itemIdCheck == 4902 or $itemIdCheck == 4905 or $itemIdCheck == 4899 or $itemIdCheck == 4901 or $itemIdCheck == 4900 or $itemIdCheck == 4879 or $itemIdCheck == 4903 or $itemIdCheck == 5854 or $itemIdCheck == 6012): ?>
<style type="text/css">

.main-region hr {
	display: none;
}

.resource.show #resource-values {
width: 100%;
}

.resource.show .values .resource-link:hover {
    transform: scale(1.2);
    display:inline-block;
}
.metadata .value.resource .resource-link {
    transition: transform .2s ease-out;
    display:block;
    text-align: center;
    width: 300px;
    
}

.resource-link img {
  max-width: inherit;
}

   .metadata .value.resource img {
        width: 300px !important;
        height: auto;
    }

    .media-embeds img {
        width: 400px !important;
        height: auto;
    }


     .item_sets {
         display:inline-block;
         width: 320px;
         padding: 20px;
     }

     h4 {
         display: none;
     }

     .media-embeds {
          display:none;
     }

.media-list {
display:none;
}

.site-pages {
display:none;
}

#linked-resources {
display:none;
}

#resources-linked {
display:none;
}

.uv {
  font-size: 16px;
}

.metadata dl > .property dd:not(.sidebar-region .metadata dl > .property dd){
margin-left: 20px;
font-size: larger;
}

.metadata dl > .property dt:not(.sidebar-region .metadata dl > .property dt) {
  float: none;
    width: 100%;
    font-size: larger;
    display: none;
}

.metadata > dl:nth-child(3) > div:nth-child(1) > dd:nth-child(2) > span:nth-child(1) {
  display: none;
}
</style>
 
<?php endif; ?>

<!-- 
end of exception
-->


<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

// Regions
$mainBlockContent = $this->resourcePageBlocks($item);
$mainHasBlocks = $mainBlockContent->hasBlocks();
$leftSidebarBlockContent = $this->resourcePageBlocks($item, 'left');
$leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
$rightSidebarBlockContent = $this->resourcePageBlocks($item, 'right');
$rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();
?>

<?php echo $this->ResourceTags($item); ?>
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 1); ?>

<?php $this->trigger('view.show.before'); ?>

<?php if ($mainHasBlocks || $leftSidebarHasBlocks || $rightSidebarHasBlocks): ?>

    <?php
    $additionalContainerClasses = '';
    if ($mainHasBlocks && $leftSidebarHasBlocks && $rightSidebarHasBlocks) {
        $additionalContainerClasses = 'regions-container--all';
    } elseif ($mainHasBlocks && !$leftSidebarHasBlocks && !$rightSidebarHasBlocks) {
        $additionalContainerClasses = 'regions-container--main';
    }
    ?>

    <div class="regions-container <?php echo $additionalContainerClasses; ?>">
        <?php if ($leftSidebarHasBlocks && $blockContent = $leftSidebarBlockContent->getBlocks()): ?>
            <div class="sidebar-region sidebar-region--left">
                <div class="metadata">
                    <?php echo $blockContent; ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($mainHasBlocks && $blockContent = $mainBlockContent->getBlocks()): ?>
            <div class="main-region">
                <div class="metadata">
                    <?php echo $blockContent; ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($rightSidebarHasBlocks && $blockContent = $rightSidebarBlockContent->getBlocks()): ?>
            <div class="sidebar-region sidebar-region--right">
                <div class="metadata">
                    <?php echo $blockContent; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>

<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
