<?php
$resourceMedia = $resource->media();
$decoration = $this->themeSetting('image_decoration');
?>
<?php if ($resourceMedia): ?>
<div class="media-embeds <?php echo is_array($decoration) && in_array('media', $decoration) ? 'decoration' : ''; ?>">
    <?php foreach ($resourceMedia as $media): 
    
          $altText = $media->altText() ?: $media->displayTitle() ?: '';
          echo $media->render(['thumbnailAttribs' => ['alt' => $altText]]);
    
          if (sizeof($media->values())>1 || sizeof($resourceMedia)>1):
            echo $media->displayValues([
    'excludeProperties' => ['dcterms:created']
]);
          endif;
    
    ?>
    <?php endforeach; ?>
</div>
<hr />
<?php endif; ?>
