<?php
$siteTitle = $site->title();
$userBar = $this->userBar();
$header_layout = ($this->themeSetting('header_layout')) ?? 'inline';
$body_class = 'main-header--' . $header_layout;
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerHeading = $this->themeSetting('banner_heading');
$bannerDescription = $this->themeSetting('banner_description');
$bannerHeightProperty = $bannerHeading || $bannerDescription ? 'min-height' : 'height';
$primaryColor = $this->themeSetting('primary_color') ?? '#B7410E';
$secondaryColor = $this->themeSetting('secondary_color') ?? '#394f68';
$accentColor = $this->themeSetting('accent_color') ?? '#394f68';

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap');
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

$this->headLink()->appendStylesheet($this->assetUrl('css/custom.css?ver=22'));     

$this->jsTranslate();
$this->trigger('view.layout');

if ($userBar) {
	$this->htmlElement('body')->appendAttribute('class', 'user-bar');
}
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>

		<style media="screen">
			:root {
				--primary: <?php echo $primaryColor; ?>;
				--primary-dark: <?php echo $this->ShadeColor($primaryColor, -10); ?>;
				--primary-contrast: <?php echo $this->ContrastColor($primaryColor, ['#fff', '#333']); ?>;
				--secondary: <?php echo $secondaryColor; ?>;
				--secondary-dark: <?php echo $this->ShadeColor($secondaryColor, -10); ?>;
				--secondary-contrast: <?php echo $this->ContrastColor($secondaryColor, ['#fff', '#333']); ?>;
				--accent: <?php echo $accentColor; ?>;
				--accent-dark: <?php echo $this->ShadeColor($accentColor, -10); ?>;
			}
			
			<?php if($bannerHeightMobile): ?>
				@media screen and (max-width:768px) {
					.banner {
						<?php echo "{$bannerHeightProperty}: {$bannerHeightMobile} !important;"; ?>
					}
				}
			<?php endif; ?>
		</style>
		
				<script defer data-domain="archiviomemoria.ecomuseovalledeilaghi.it" src="https://statistichearchiviomemoria.ecomuseovalledeilaghi.it/js/script.js"></script>
	</head>

	<?php echo $this->htmlElement('body')->appendAttribute('class', $body_class); ?>
		<a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

		<?php echo $this->partial('common/header', ['userBar' => $userBar, 'site' => $site]); ?>

		<?php echo $this->partial('common/banner'); ?>

            <!-- modifica homepage -->
<?php
$path =  $_SERVER["REQUEST_URI"];
   
if ($path == "/s/archivio/page/homepage"): ?>
<style type="text/css">
::placeholder { 
font-size:1em;
font-style: normal;
}

input[type="text"] {
 font-size:1em;
}

#search {
display:none;
}

#main-content {
	padding-bottom: 0rem;
}

</style>

<div style="background-image: url('/themes/freedom_amevl/asset/img/old_letters.jpg');background-size: cover;background-position: center;padding-bottom:100px;padding-top:80px;margin-top:0px;">

<div id="centerwhiteboxcover">
<div id="whiteboxcover">
<h2 style = "text-align:center;">COSA STAI CERCANDO?</h2>
            <div id="search-homepage" style="text-align:center;font-size:2em;display:inline-block;">
              <div class="search">
                <?php echo $this->partial('common/search-form-homepage'); ?>
            </div>
            <div id = "testosottoboxricercahomepage">
            <b><a href="/s/pubblicazioni-sulla-valle-dei-laghi/page/home-page">Per cercare tra le pubblicazioni, visita la sezione dedicata</a></b></div>
          </div>
          </div>  
            
            </div></div></div>

                <?php else: ?>
                <style type="text/css">
                
                #mostreapprofondimenti img {
                width: 250px;
                }


                </style>
               
                <?php endif; ?>



  <!-- fine modifica homepage -->
            


		<div id="content" class="container" role="main" tabindex="-1">
			<?php echo $this->content; ?>
		</div>

		<?php echo $this->partial('common/footer'); ?>

		<?php
		echo $this->inlineScript()
			->prependFile($this->assetUrl('js/navigation.js'))
			->prependFile($this->assetUrl('js/script.js'));
		?>
	</body>
</html>
